language: python

python:
  - 3.6
services:
  - docker

os:
  - linux
    

notifications:
  email: true

before_install:
  - docker build -t pns .
script:
  - docker run pns python $HOME/work/PyPNS/test.py